version: '3'
services:
  selenoid:
    hostname: 'selenoid'
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD:/etc/selenoid/"
      - "$PWD:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  jenkins:
    hostname: 'my.jenkins.com'
    network_mode: bridge
    image: jenkins/jenkins:latest
    volumes:
      - "${PWD}/work/jenkins:/var/jenkins_home"
    ports:
      - "8000:8080"
    restart: always

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    ports:
      - "6942:8080"
    volumes:
      - '${PWD}/gitlab/config:/etc/gitlab'
      - '${PWD}/gitlab/logs:/var/log/gitlab'
      - '${PWD}/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
